import cron from 'node-cron';
import { Child } from '../models/Child';
import { Attendance } from '../models/Attendance';
import { Evaluation } from '../models/Evaluation';
import { Report } from '../models/Report';
import { User } from '../models/User';

/**
 * Generate daily reports for all active children
 * This function runs automatically via cron job
 */
export const generateDailyReports = async (): Promise<void> => {
    try {
        console.log('[CRON] Starting daily report generation...');

        // Get or create a system user for auto-generated reports
        let systemUser = await User.findOne({ username: 'system' });
        if (!systemUser) {
            console.log('[CRON] System user not found, creating one...');
            systemUser = await User.create({
                username: 'system',
                email: 'system@childcare.local',
                password: 'system-auto-generated',
                fullName: 'System Auto-Generator',
                role: 'ADMIN',
                phoneNumber: '0912345678',
                isActive: true,
            });
        }

        // Get all active children
        const activeChildren = await Child.find({ status: 'ACTIVE' });
        console.log(`[CRON] Found ${activeChildren.length} active children`);

        // Get today's date range (start and end of day)
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        const endOfDay = new Date(today);
        endOfDay.setHours(23, 59, 59, 999);

        let reportsGenerated = 0;

        // Generate report for each child
        for (const child of activeChildren) {
            try {
                // Get attendance data for today
                const attendance = await Attendance.find({
                    childId: child._id,
                    date: {
                        $gte: today,
                        $lte: endOfDay,
                    },
                });

                const attendanceStats = {
                    totalDays: attendance.length,
                    presentDays: attendance.filter((a) => a.status === 'PRESENT').length,
                    absentDays: attendance.filter((a) => a.status === 'ABSENT').length,
                    lateArrivals: attendance.filter((a) => a.status === 'LATE').length,
                };

                // Get evaluations for today
                const evaluations = await Evaluation.find({
                    childId: child._id,
                    date: {
                        $gte: today,
                        $lte: endOfDay,
                    },
                }).select('_id');

                // Create daily report
                await Report.create({
                    type: 'DAILY',
                    childId: child._id,
                    generatedBy: systemUser._id,
                    isAutoGenerated: true,
                    period: {
                        startDate: today,
                        endDate: endOfDay,
                    },
                    data: {
                        attendance: attendanceStats,
                        evaluations: evaluations.map((e) => e._id.toString()),
                        activities: [],
                        healthIncidents: [],
                    },
                });

                reportsGenerated++;
            } catch (error: any) {
                console.error(`[CRON] Error generating report for child ${child._id}:`, error.message);
            }
        }

        console.log(`[CRON] Daily report generation completed. Generated ${reportsGenerated} reports.`);
    } catch (error: any) {
        console.error('[CRON] Error in daily report generation:', error.message);
    }
};

/**
 * Initialize and start all scheduled jobs
 */
export const initializeScheduledJobs = (): void => {
    console.log('[CRON] Initializing scheduled jobs...');

    // Schedule daily report generation at 11:59 PM every day
    // Cron format: second minute hour day month weekday
    // '59 23 * * *' = At 11:59 PM every day
    const dailyReportSchedule = process.env.DAILY_REPORT_CRON_SCHEDULE || '59 23 * * *';

    cron.schedule(dailyReportSchedule, async () => {
        console.log('[CRON] Daily report cron job triggered');
        await generateDailyReports();
    });

    console.log(`[CRON] Daily report generation scheduled: ${dailyReportSchedule}`);
    console.log('[CRON] All scheduled jobs initialized successfully');
};

/**
 * Stop all scheduled jobs (for graceful shutdown)
 */
export const stopScheduledJobs = (): void => {
    console.log('[CRON] Stopping all scheduled jobs...');
    cron.getTasks().forEach((task) => task.stop());
    console.log('[CRON] All scheduled jobs stopped');
};
