import mongoose, { Schema } from 'mongoose';
import { IReport } from '../types';

const ReportSchema = new Schema<IReport>(
  {
    type: {
      type: String,
      enum: ['WEEKLY', 'MONTHLY', 'YEARLY'],
      required: [true, 'Report type is required'],
    },
    childId: {
      type: String,
      ref: 'Child',
    },
    generatedBy: {
      type: String,
      required: [true, 'Generated by is required'],
      ref: 'User',
    },
    period: {
      startDate: {
        type: Date,
        required: true,
      },
      endDate: {
        type: Date,
        required: true,
      },
    },
    data: {
      attendance: {
        totalDays: Number,
        presentDays: Number,
        absentDays: Number,
        lateArrivals: Number,
      },
      evaluations: [String],
      activities: [String],
      healthIncidents: [String],
    },
  },
  {
    timestamps: true,
  }
);

// Index for faster queries
ReportSchema.index({ childId: 1, createdAt: -1 });
ReportSchema.index({ generatedBy: 1 });

export const Report = mongoose.model<IReport>('Report', ReportSchema);

